FROM ubuntu:16.04

RUN set -e \
    && apt-get update \
    && apt-get install -y \
                        python3 \
                        python3-pip

COPY . /app
WORKDIR /app

RUN pip3 install -r requirements.txt


VOLUME /app

COPY entrypoint.sh /entrypoint.sh
RUN chmod +x /entrypoint.sh
ENTRYPOINT ["/entrypoint.sh"]
