version: "2"

services:
    ubuntu:
        build:
            context: .
            dockerfile: Dockerfile-ubuntu
        container_name: cert_ubuntu
    debian:
        build:
            context: .
            dockerfile: Dockerfile-debian
        container_name: cert_debian
